include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "gnome-taquin-nightly.flatpak"

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "build-aux/org.gnome.Taquin.json"
        FLATPAK_MODULE: "gnome-taquin"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Taquin"
    extends: .flatpak
