include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "gnome-taquin-nightly.flatpak"

flatpak:
    variables:
        MANIFEST_PATH: "build-aux/org.gnome.Taquin.json"
        FLATPAK_MODULE: "gnome-taquin"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Taquin"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak']
    needs: ['flatpak']
